/* -*- mode: c++ -*- */
// \file CATAlgorithm/SULTAN_config.h

#ifndef CATALGORITHM_SULTAN_CONFIG_H
#define CATALGORITHM_SULTAN_CONFIG_H 1

#define SULTAN_VERSION 0.3.4

#define SULTAN_WITH_DEVEL_UTILS 0
#define SULTAN_WITH_DEVEL_DISPLAY 0
#define SULTAN_WITH_DEVEL_HISTOGRAMS 0
#define SULTAN_WITH_DEVEL_ROOT 0

#endif  // CATALGORITHM_SULTAN_CONFIG_H
