
[urn="urn:snemo:demonstrator:geometry:default" category="varprofile"]
  description              : string    = "Default geometry setup for the SuperNEMO demonstrator"
  topics                   : string[1] = "alias_of"
  topic.alias_of.component : string    = "urn:snemo:demonstrator:geometry:5.1"

[urn="urn:snemo:demonstrator:setup:default" category="varprofile"]
  description              : string    = "Default experimental setup for the SuperNEMO demonstrator model"
  topics                   : string[1] = "alias_of"
  topic.alias_of.component : string    = "urn:snemo:demonstrator:setup:2.1"

[urn="urn:snemo:demonstrator:simulation:default" category="varprofile"]
  description              : string    = "Default simulation setup for the SuperNEMO demonstrator"
  topics                   : string[1] = "alias_of"
  topic.alias_of.component : string    = "urn:snemo:demonstrator:simulation:2.5"

[urn="urn:snemo:demonstrator:reconstruction:default" category="varprofile"]
  description              : string    = "Default simulation setup for the SuperNEMO demonstrator"
  topics                   : string[1] = "alias_of"
  topic.alias_of.component : string    = "urn:snemo:demonstrator:reconstruction:3.1"
